### ISSUE TITLE
Font does not compatible with all languages

### ISSUE THREAD

**Issue by ngxson** [soyket/void-elementor-post-grid-addon-for-elementor-page-builder#3]
Please stop using custom font. `Poppins` does not compatible with all languages

https://github.com/soyket/void-elementor-post-grid-addon-for-elementor-page-builde/blob/7692fd2cbaa5ce568c3d08374332521f2ece7273/assets/css/main.css#L19

**Comment by dev-sayem** [comment]
@ngxson 
Sorry for this kind of inconvenience. We included a typography change control for every kind of text. You can change your desired font for your specific language. Let us know do you have any other problems.
Thank you.
